### ISSUE TITLE
Building and Running

### ISSUE THREAD

**Issue by LuisFX** [jamieday/FunkyTetris#1]
Sweet Project!

I'm having an issue getting it to build/run. Here's my env:

Mac OS
npm -v: 3.10.10
node -v: v6.14.4
dotnet --version: 2.1.302
yarn -v: 1.9.4

dotnet restore: completes.
dotnet fable yarn-start
 ERROR:
../FunkyTetris/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');

**Comment by jamieday** [comment]
Thanks @LuisFX 

I cloned the project in a fresh directory on my machine to see if I missed any necessary source files but everything seems to run fine on my end. Unfortunately I don't have access to a mac to reproduce your conditions.

Are you able to run other Fable projects / templates with no issues?

Sample Fable template: https://github.com/fable-compiler/fable-templates/blob/d1759f7058fc519485ce8bcd62521890573539c6/simple/Content/README.md

One thing I noticed in the above is that it states that mono is required for Paket on macOS & Linux.

**Comment by jrr** [comment]
fwiw it works just fine for me, on mac:

```
jrr@jrrmbp ~/r/FunkyTetris (master)> yarn
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[#####################################################------------] 17103/20827c
[4/4] 📃  Building fresh packages...
✨  Done in 7.70s.
jrr@jrrmbp ~/r/FunkyTetris (master)> cd src
jrr@jrrmbp ~/r/F/src (master)> dotnet restore
  Restore completed in 31.61 ms for /Users/jrr/repos/FunkyTetris/src/FunkyTetris.fsproj.
  Restore completed in 72.36 ms for /Users/jrr/repos/FunkyTetris/src/FunkyTetris.fsproj.
jrr@jrrmbp ~/r/F/src (master)> dotnet fable yarn-start
Fable (1.3.3) daemon started on port 61225
CWD: /Users/jrr/repos/FunkyTetris
yarn run start
yarn run v1.9.4
$ webpack-dev-server
Bundling for development...
Project is running at http://localhost:8080/
```

Maybe the nodejs version?
```
jrr@jrrmbp ~/r/F/src (master) [130]> node --version
v8.11.3
```

**Comment by LuisFX** [comment]
Ok, so I cloned another copy into my userspace... bam, works! It might be an environment issue at my end. 

Thanks!
