### ISSUE TITLE
Not an issue. Favicon.

### ISSUE THREAD

**Issue by LuisFX** [jamieday/FunkyTetris#2]
What would a good idea for a favicon be?

I was thinking something like a "T" made out blocks that resemble the Fsharp logo. Or something like blocky lamda glyph.

**Comment by jrr** [comment]
The (hilarious and game-breakingly terrible) lambda block would be a good candidate.

**Comment by LuisFX** [comment]
![favicon-128](https://user-images.githubusercontent.com/1130772/45710538-bf322800-bb3b-11e8-98b9-e1dbe68a8728.png)

**Comment by jamieday** [comment]
Definitely on board with this, @LuisFX your image looks great

**Comment by jamieday** [comment]
See https://github.com/jamieday/FunkyTetris/pull/3
